# Filename: .bash_profile
# Directory: ~/

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
if [ -d ~/.pyenv ]; then
	export PYENV_ROOT="$HOME/.pyenv";
	command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH";
	eval "$(pyenv init -)";
fi
